### ISSUE TITLE
Sort by Requirements

### ISSUE THREAD

**Issue by UmbraZeal** [illandril/FoundryVTT-inventory-sorter#122]
**Describe the solution you'd like**
Sorting alphabetical but by the requirements tab.

**What system(s) do you want this feature to work with?**
DnD5e - Fifth Edition System

**Additional context**
![caf45e3d6d7fae9cef5d2b566b991165](https://github.com/illandril/FoundryVTT-inventory-sorter/assets/112840716/3ad61f32-edfd-42b0-8874-297bcfa6deb5)

**Comment by illandril** [comment]
Note: Sorting might not always feel "natural" for class levels ("Paladin 10" will appear between "Paladin 1" and "Paladin 2", as opposed to after "Paladin 9").

I've written an issue to improve this (#123), but I likely won't resolve this any time soon.
