### ISSUE TITLE
Compatibility with the new Tidy Sheet

### ISSUE THREAD

**Issue by SagaTympana** [illandril/FoundryVTT-inventory-sorter#161]
**Is your feature request related to a problem? Please describe.**
With kgar's new version of TidySheet, Inventory Sorter doesn't function without the Legacy Mode setting enabled.

**Describe the solution you'd like**
I would like the non-legacy sorting features to function when using kgar's Tidy Sheet character sheet module.

**Describe alternatives you've considered**
Legacy mode does allow basic sorting to function, but the description of that setting warned that it would probably be going away and make a feature request on this GitHub page ;P

**What system(s) do you want this feature to work with?**
DnD5e - Fifth Edition System

**What other modules do you use that you want to ensure work well with this feature?**
Tidy 5e Sheets (kgar alpha)

**Additional context**
[Tidy 5e Sheets](https://github.com/kgar/foundry-vtt-tidy-5e-sheets)

**Comment by illandril** [comment]
Note: Since the Kgar sheets are in alpha, it wouldn't be too surprising if changes are made to them that break compatibility between now and when those sheets are fully released.
