### ISSUE TITLE
Features tab not sorting properly

### ISSUE THREAD

**Issue by Avitale34** [illandril/FoundryVTT-inventory-sorter#2]
With the newest update I noticed the features section is not sorting automatically.

**Comment by illandril** [comment]
Which sheet(s) are you seeing this issue with?

For me, the Default Character Sheet works fine, but the default NPC sheet is broken (for both Features and Spells). However, the NPC sheet's sorting is broken even with all modules disabled - clicking and dragging features doesn't reposition them on the NPC sheet as it does everywhere else (making this a bug in the DnD5e system, which I have written up as an issue for Atropos here: https://gitlab.com/foundrynet/dnd5e/-/issues/824).
